using System;
using System.ComponentModel;
using System.Drawing;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using CommunityToolkit.Mvvm.DependencyInjection;
using Leonardo.Models.Interfaces;
using Leonardo.ViewModels.Interfaces;
using BaseLib.Interfaces;

namespace Leonardo.ViewModels;

/// <summary>
/// ViewModel implementation for the Leonardo application following the MVVM pattern.
/// This class serves as the intermediary between the view and the model, handling user interactions
/// and coordinating operations such as image encoding, decoding, and AI-based image generation.
/// </summary>
/// <remarks>
/// <para>
/// The <see cref="LeonardoViewModel"/> class utilizes the CommunityToolkit.Mvvm library for
/// implementing observable properties and relay commands, reducing boilerplate code.
/// </para>
/// <para>
/// This ViewModel supports dependency injection through the <see cref="CommunityToolkit.Mvvm.DependencyInjection.Ioc"/>
/// container for resolving file dialog services.
/// </para>
/// </remarks>
public partial class LeonardoViewModel : ObservableObject, ILeonardoViewModel
{
    /// <summary>
    /// The underlying model instance that contains the business logic for Leonardo operations.
    /// </summary>
    private ILeonardoClass _model;

    /// <summary>
    /// Gets or sets a delegate function that displays a file dialog to the user.
    /// </summary>
    /// <value>
    /// A function that takes an <see cref="IFileDialog"/> instance and returns <see langword="true"/>
    /// if the user confirmed the dialog; otherwise, <see langword="false"/>.
    /// Returns <see langword="null"/> if no dialog handler is assigned.
    /// </value>
    public Func<IFileDialog, bool>? ShowFileDialog { get; set; }

    /// <summary>
    /// Gets or sets a delegate function that displays an input dialog to the user.
    /// </summary>
    /// <value>
    /// A function that takes a prompt message string and returns the user's input string.
    /// Returns <see langword="null"/> if no input dialog handler is assigned.
    /// </value>
    public Func<string, string>? InputShowDialog { get; set; }

    /// <summary>
    /// Gets or sets a delegate action that displays a message box to the user.
    /// </summary>
    /// <value>
    /// An action that takes a message string to display. Returns <see langword="null"/>
    /// if no message box handler is assigned.
    /// </value>
    public Action<string>? MessageBoxShow { get; set; }

    /// <summary>
    /// Gets or sets the current cursor state for the application.
    /// </summary>
    /// <value>
    /// An <see cref="ECursor"/> enumeration value indicating the current cursor type,
    /// such as default or wait cursor. Can be <see langword="null"/>.
    /// </value>
    /// <remarks>
    /// This property is automatically generated by the <see cref="ObservablePropertyAttribute"/>
    /// and raises property changed notifications when modified.
    /// </remarks>
    [ObservableProperty]
    private ECursor? _cursorCurrent;

    /// <summary>
    /// Gets or sets the message text displayed in the user interface.
    /// </summary>
    /// <value>
    /// A string containing status messages or information to be displayed to the user.
    /// </value>
    /// <remarks>
    /// This property is automatically synchronized with the model's <c>MessageText</c> property
    /// through the <see cref="OnModelPropertyChanged"/> event handler.
    /// </remarks>
    [ObservableProperty]
    private string _messageText;

    /// <summary>
    /// Gets or sets the decoded image bitmap to be displayed in the picture box.
    /// </summary>
    /// <value>
    /// A <see cref="Bitmap"/> instance containing the decoded or generated image,
    /// or <see langword="null"/> if no image is available.
    /// </value>
    /// <remarks>
    /// This property is automatically synchronized with the model's <c>PicBoxDECImg</c> property
    /// through the <see cref="OnModelPropertyChanged"/> event handler.
    /// </remarks>
    [ObservableProperty]
    private Bitmap? _picBoxDECImg;

    /// <summary>
    /// Initializes a new instance of the <see cref="LeonardoViewModel"/> class with no model.
    /// </summary>
    /// <remarks>
    /// This parameterless constructor is primarily intended for design-time support or
    /// scenarios where the model will be injected later. The model is set to <see langword="null"/>
    /// using the null-forgiving operator.
    /// </remarks>
    public LeonardoViewModel()
    {
        _model = null!;
    }

    /// <summary>
    /// Initializes a new instance of the <see cref="LeonardoViewModel"/> class with the specified model.
    /// </summary>
    /// <param name="model">
    /// The <see cref="ILeonardoClass"/> model instance that provides the business logic
    /// for encoding, decoding, and image generation operations.
    /// </param>
    /// <remarks>
    /// <para>
    /// This constructor sets up bidirectional communication between the ViewModel and the model by:
    /// </para>
    /// <list type="bullet">
    /// <item><description>Subscribing to the model's <see cref="INotifyPropertyChanged.PropertyChanged"/> event.</description></item>
    /// <item><description>Configuring delegate callbacks for save file queries, message boxes, and input dialogs.</description></item>
    /// <item><description>Synchronizing initial property values from the model.</description></item>
    /// </list>
    /// </remarks>
    public LeonardoViewModel(ILeonardoClass model)
    {
        _model = model;
        _model.PropertyChanged += OnModelPropertyChanged;
        _model.SaveFileQuery = SaveFileQuery;
        _model.MessageBoxShow = (string message) => MessageBoxShow?.Invoke(message);
        _model.InputQuery = (string message) => InputShowDialog?.Invoke(message);
        MessageText = _model.MessageText;
        PicBoxDECImg = _model.PicBoxDECImg;
    }

    /// <summary>
    /// Handles save file dialog requests from the model.
    /// </summary>
    /// <param name="arg">
    /// The file filter string to be applied to the save file dialog
    /// (e.g., "Image Files (*.png)|*.png").
    /// </param>
    /// <returns>
    /// The selected file path if the user confirmed the dialog; otherwise, <see langword="null"/>.
    /// </returns>
    /// <remarks>
    /// This method resolves an <see cref="ISaveFileDialog"/> instance from the IoC container
    /// and displays it using the configured <see cref="ShowFileDialog"/> delegate.
    /// </remarks>
    private string? SaveFileQuery(string arg)
    {
        using IFileDialog saveFileDialog = Ioc.Default.GetRequiredService<ISaveFileDialog>();
        saveFileDialog.Filter = arg;
        if (ShowFileDialog?.Invoke(saveFileDialog) ?? false)
        {
            return saveFileDialog.FileName;
        }
        return null;
    }

    /// <summary>
    /// Handles property change notifications from the underlying model.
    /// </summary>
    /// <param name="sender">The source of the event (the model instance).</param>
    /// <param name="e">
    /// The <see cref="PropertyChangedEventArgs"/> containing the name of the changed property.
    /// </param>
    /// <remarks>
    /// This method synchronizes the ViewModel's properties with the model when changes occur,
    /// ensuring the UI remains up-to-date with the underlying data.
    /// Currently handles synchronization for <c>MessageText</c> and <c>PicBoxDECImg</c> properties.
    /// </remarks>
    private void OnModelPropertyChanged(object sender, PropertyChangedEventArgs e)
    {
        switch (e.PropertyName)
        {
            case nameof(_model.MessageText):
                MessageText = _model.MessageText;
                break;
            case nameof(_model.PicBoxDECImg):
                PicBoxDECImg = _model.PicBoxDECImg;
                break;
        }
    }

    /// <summary>
    /// Executes the encoding operation by prompting the user to select an image file
    /// and encrypting data into it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This command performs the following steps:
    /// </para>
    /// <list type="number">
    /// <item><description>Resolves an open file dialog from the IoC container.</description></item>
    /// <item><description>Filters for PNG and JPG image files.</description></item>
    /// <item><description>If a file is selected, delegates to the model's <c>PromptAndEncrypt</c> method.</description></item>
    /// </list>
    /// </remarks>
    [RelayCommand()]
    private void Encode()
    {
        using IFileDialog openFileDialog = Ioc.Default.GetRequiredService<IOpenFileDialog>();
        openFileDialog.Filter = "Image Files (*.png, *.jpg)|*.png;*.jpg;";
        if (ShowFileDialog?.Invoke(openFileDialog) ?? false)
        {
            string fileName = openFileDialog.FileName;
            _model.PromptAndEncrypt(fileName);
        }
    }

    /// <summary>
    /// Executes the decoding operation by prompting the user to select an image file
    /// and decrypting data from it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This command performs the following steps:
    /// </para>
    /// <list type="number">
    /// <item><description>Resolves an open file dialog from the IoC container.</description></item>
    /// <item><description>Filters for PNG and JPG image files.</description></item>
    /// <item><description>If a file is selected, delegates to the model's <c>PromptAndDecrypt</c> method.</description></item>
    /// </list>
    /// </remarks>
    [RelayCommand()]
    private void Decode()
    {
        using IFileDialog openFileDialog = Ioc.Default.GetRequiredService<IOpenFileDialog>();
        openFileDialog.Filter = "Image Files (*.png, *.jpg)|*.png;*.jpg;";
        if (ShowFileDialog?.Invoke(openFileDialog) ?? false)
        {
            string fileName = openFileDialog.FileName;
            _model.PromptAndDecrypt(fileName);
        }
    }

    /// <summary>
    /// Executes the AI image generation and encryption operation using a user-provided prompt.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This command performs the following steps:
    /// </para>
    /// <list type="number">
    /// <item><description>Sets the cursor to a wait cursor to indicate processing.</description></item>
    /// <item><description>Prompts the user for a Stable Diffusion prompt via input dialog.</description></item>
    /// <item><description>If a valid prompt is provided, sends a request to the Hugging Face API for image generation with encryption.</description></item>
    /// <item><description>If no prompt is provided, displays an error message to the user.</description></item>
    /// </list>
    /// <para>
    /// Any exceptions during execution are caught and logged to the console.
    /// </para>
    /// </remarks>
    [RelayCommand()]
    private void Generate()
    {
        try
        {
            CursorCurrent = ECursor.WaitCursor;
            string text = InputShowDialog("SD prompt");
            if (!string.IsNullOrEmpty(text))
            {
                _model.HuggingRequest2ENC(text);
            }
            else
            {
                MessageBoxShow("Please enter a string to encrypt.");
            }
        }
        catch (Exception ex)
        {
            Console.WriteLine("Error: " + ex.Message);
        }
    }

    /// <summary>
    /// Executes a test request to the Hugging Face API asynchronously.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This command is intended for testing purposes and triggers an asynchronous
    /// request to the Hugging Face service through the model.
    /// </para>
    /// <para>
    /// <b>Warning:</b> This method uses <c>async void</c> which should generally be avoided
    /// except for event handlers, as exceptions cannot be properly awaited or caught by the caller.
    /// </para>
    /// </remarks>
    [RelayCommand()]
    private async void Test()
    {
        await _model.HuggingRequest();
    }

    /// <summary>
    /// Sets the console instance for the underlying model to enable console output.
    /// </summary>
    /// <param name="console">
    /// The <see cref="IConsole"/> implementation to be used for console operations.
    /// </param>
    /// <remarks>
    /// This method delegates directly to the model's <c>SetConsole</c> method,
    /// allowing the model to output messages to the specified console implementation.
    /// </remarks>
    public void SetConsole(IConsole console) => _model.SetConsole(console);
}